# Generated by Django 3.1.2 on 2020-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201220_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
